baseURL = "https://batscheck.at.eu.org"
title = "Batscheck Bryanzaeff"
languageCode = "en-us"
defaultContentLanguage = "es"
paginate = "7"
#theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "<img src='https://bafybeih2aouwlgweq6wzbk7lgtkfsqgkhwr6ss2kpadajibcikdmaw2apq.ipfs.nftstorage.link/logo.svg' width='100' height='100'/> <br /> Batscheck Bryanzaeff" # title for frontpage, may include image
copyright = "Batscheck Bryanzaeff"
description = 'Experiencia, dedicación y compromiso.'
startbuttonText = "Empezar"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
images = ["/static/img/"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.60.0"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = './posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Nosotros'
body = '''
El Estudio Batscheck Bryanzeff Abogados, es una organización creada y orientada a brindar asistencia jurídica a personas y empresas en diversas ramas del Derecho Contemporáneo y especialmente en materia de Derecho Asegurador, Derecho de Daños, Derecho Cooperativo, Financiero, Derecho Laboral y Derecho Procesal o Litigios en general”

Desde sus inicios nuestro Estudio se ha destacado como un referente de conocimiento, experiencia y confiabilidad en el mundo de las Empresas y Seguros. Este ha sido el punto de partida para su activa participación y especialización en diferentes ámbitos de la ciencia jurídica, donde siempre se ha esforzado por acompañar a sus clientes en el logro pleno de sus objetivos.
'''

[[params.one.icon]]
icon = "solid fa-money-check"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "solid fa-landmark"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-people-group"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
img_alt = "blurry background: white/grey"
title = 'INFRAESTRUCTURA'
body = '''
Nuestras instalaciones están pensadas y diseñadas para brindar, a nuestros clientes y amigos una atención personalizada y una asesoría ajustada a las necesidades del mundo moderno. En tal sentido nuestra organización cuenta con herramientas tecnológicamente ajustadas a las cambiantes necesidades, una biblioteca dotada de variados títulos nacionales e internacionales de los más prestigiosos juristas que hacen a las diversas ramas de la ciencia jurídica en la que nuestro Estudio se desenvuelve. Suscriptos a importantes revistas semanales, mensuales y anuales, permiten comprometernos con la más reciente doctrina y con los adelantos jurisprudenciales referidos a los temas que son de la especialidad del Estudio Jurídico.
'''

[[params.two.section]]
img = "img/pic02.jpg"
title = ''
body = '''
Todo cuanto hemos referido en el presente material da cuentas de una fuerte inversión en un histórico edificio ubicado en 12 de octubre 327 de la Ciudad de Asunción, destinado a prestar un servicio ajustado a las cambiantes y modernas necesidades del mundo globalizado, todo ello con un solo objetivo, cual es, el de lograr una solución eficiente eficaz y positiva a los intereses de nuestros clientes.
'''
#
#[[params.two.section]]
#img = "img/pic03.jpg"
#title = 'Magna primis lobortis<br />sed ullamcorper'
#body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'
#
[params.three]
enable = true
title = 'EXPERIENCIA'
body = '''
Acumulada desde su inicio atendiendo a una diversa cantidad de empresas y particulares con problemáticas y necesidades de distinta índole.

Asumiendo los valiosos aportes para su desarrollo personal, profesional y académico, nuestra preocupación siempre ha sido desempeñar la docencia en importantes universidades e institutos de enseñanza de nuestro país en temas vinculados a la especialidad del Estudio, como también la participación en numerosos congresos y seminarios locales e internacionales en calidad de conferencista.

Generadora de un enriquecedor intercambio, la presencia en el ámbito académico es fuente de una actualización activa y constante que es luego encauza-da hacia los requerimientos de los clientes.
'''

[[params.three.feature]]
icon = "solid fa-wallet"
title = "Recupero de Créditos"
body = '''
El que puede darse por la vía extrajudicial o judicial. La primera de ellas, que incluye servicio de cobranza con móviles y comunicación radial incluida que permite el contacto permanente entre los diferentes estamentos de nuestra organización. En lo que a reclamo judicial se refiere, contamos con una vasta experiencia en litigios de ésta naturaleza.-
'''

[[params.three.feature]]
icon = "solid fa-book-open"
title = "DERECHO CIVIL"
body = '''
El Estudio cuenta con profesionales en condiciones de producir todo tipo de intervenciones y acuerdos vinculadas a sociedades, sucesiones, obligaciones en general, personas y derechos reales.
'''

[[params.three.feature]]
icon = "solid fa-cookie-bite"
title = "DEFENSA DEL CONSUMIDOR"
body = '''
Consientes que las relaciones contractuales pueden estar influenciadas por cláusulas abusivas que violan las garantías de defensa al consumidor, el Estudio ha desarrollado éste perfil de atención, con miras a proteger al consumidor.
'''


[[params.three.feature]]
icon = "solid fa-shield-halved"
title = "DERECHO ASEGURADOR"
body ='''

Nuestra vasta experiencia en seguros y especialización en el tema, nos llevó a participar en los más variados litigios y en el asesoramiento a un número importante de empresas de seguros y particulares.
'''

[[params.three.feature]]
icon = "solid fa-car-burst"
title = "REASEGUROS"
body = "Con un importante conocimiento técnico, jurídico y académico, nos encontramos en condiciones de asumir, todo lo que tiene que ver con el seguimiento y asesoramiento, preventivo permanente, de toda cuestión vinculada a las condiciones contractuales reaseguradoras y por sobre todo, asistencia y representación en discusiones arbitrales y en procesos donde se sustancian relaciones jurídicas litigiosas."

[[params.three.feature]]
icon = "solid fa-file-signature"
title = "CAUCIÓN"
body = "El conflictivo universo de ideas que genera ésta herramienta obliga a estar a la vanguardia de todo cuanto implica el análisis y asesoramiento de ésta rama de la ciencia del derecho asegurador. Nuestro Estudio se encuentra en sobrad as condiciones de generar respuestas serias, rápidas y ajustadas a las necesidades."

[[params.three.feature]]
icon = "fa-flag"
title = "RESPONSABILIDAD CIVIL"
body = "Hemos hecho una especialidad de ésta."

[[params.three.feature]]
icon = "fa-flag"
title = "vacio"
body = '''
llenar
'''

[params.cta]
enable = true
title = "SATISFACCIÓN"
body = ''''
Estamos en la permanente búsqueda de la mejora de nuestros servicios.
'''

[[params.cta.link]]
href = "mailto:abogados@batscheck.com.py"
text = "e-mail"
special = true

[[params.cta.link]]
href = "#"
text = "Atrás.."
special = false

[params.contact]
enable = true
title = "Contáctenos"
body = "Apreciamos contar con tu opinión y percepción de los mismos. También nos interesan sus expectativas para así obtener los resultados buscados. En ese sentido le solicitamos que cualquier opinión que tenga."
phone = "+595980000000"
address = "12 de Octubre 327 casi 11 de diciembre. <br />Asunción <br /> Paraguay."
email = "batscheck@batscheck.com.py"
subject = "Nuevo Mensaje"
formspree_form_id = "CZ5NNMFpsgxFFvgbXlK8jK5FL1OYkcnvqiS9CQ1KIjOc9vgNz5Y="

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 10
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 0
languageName = "Español"
